=== tomneutens/test_learning_content/learning_path_definition_schema.json
{
    "$id": "https://dwengo.org/learning_track.schema.json",
    "$schema": "http://json-schema.org/draft-07/schema",
    "title": "Schema for definition of learning track",
    "type": "object",
    "properties":{
        "language": {
            "title": "The language used in the learning track",
            "type": "string"
        },
        "title": {
            "title": "The title of the learning track",
            "type": "string"
        },
        "description": {
            "title": "The description of the learning track",
            "type": "string"
        },
        "image": {
            "title": "Base64 encoding of cover image",
            "type": "string"
        },
        "nodes": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "learningobject_id": {
                        "type": "string"
                    },
                    "language": {
                        "type": "string"
                    },
                    "version": {
                        "type": "string"
                    },
                    "instruction": {
                        "type": "string"
                    },
                    "start_node": {
                        "type": "boolean"
                    },
                    "transitions": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "condition": {
                                    "type": "string"
                                },
                                "next": {
                                    "type": "string"
                                },
                                "default": {
                                    "type": "boolean"
                                }
                            },
                            "required": ["next"]
                        }
                    }
                },
                "required": ["learningobject_id", "language", "version"]
            },
            "minItems": 1
        }

    },
    "required": ["language", "nodes"]
}

=== tomneutens/test_learning_content/learning_path_example.json
{
	"language": "nl",
    "title": "test",
    "description": "test description",
    "image": "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wgARCAQaBXgDASIAAhEBAxEB/8QAGwAAAgMBAQEAAAAAAAAAAAAAAAECAwQFBgf/xAAaAQEBAQEBAQEAAAAAAAAAAAAAAQIDBAUG/9oADAMBAAIQAxAAAAH1yF9DkxMGiRgqYgbTACBxGpiRMhOVpodtJJrWQl0PM61mNRts5jk6tdFmbKVKstritJBatVWjNJlqapASsAGEoxgpKWJIFYaLJX57rLKpVxY4WCptoLWpLBQpjdGiwhZG+s2bXmzbLYzRV3KVQlkl1UYYF9Q5oY116uZfZ1Xm0VCULFM2jPFWineZK9kKqWlpjeiEQcq7FZSkvrjUWSpmk6p4yeNwUAlAAAABAAAEenLq0vjbGxaKomuGe6K5X6F5kOrWvOl0aVzEooxMABAqAAAGJgAIEEWpEAAAAiNdtZVC2tIsEADpJr05BCNxcNADRbITkQSlRonLkaKcouWQ4w2mJAOLiRUkAkkhRNF+FHWhy5ZdJc6FX0JAACdstLtrUBwpDUTZFuUaLLIXMZ1TCrRBaydyZqehihUQzS2QQshNRpEoohkUkoClAIGpK5RnK2mo4lW35A6l/Fiehp41pv28e6t1WUOi+ZmrqvkWx04jsqsptkKrabFFhVn2VnOjuxQgSjQAAAIAAAj3YNNbCmzWb2C0F0yjQs5onktXc4LLKzTbgXTxlA4gCACgAGMQ0IEJNSIbE2hRnEjGSK67a0gnFGAdFM9OEDExDFITbWLtsyrutnzQUM1QQbOcL5dELp87z49OisashpFSiCaRKSEhDTQhpEAJjhMcr1FpDDooaBuVMYMIGkdQ5jTbZzXHRpw57OkcpLqzxIEyBpgAqGhKURJqUTUoDCTs5dISyc/zenuLLd5+7u5803wrt784qWazUUa94rJw78hM3hA6GlVl2ZJuvy7Lko1UpXKVRYssTVztUDCSjKgAAAaAYiAsLK2brcnS1KJXUJLTjmXQjOpyspmoVND15JG6iazSjZSYicNEAAAxFNNSCYJSAZIipREmiClAhXZXJGMoohh0QPTgTQwYpPRlTdprzVbVLK8reFVWmvbCmuh7cerK+SfLUoWuMteinozQ0Valablir2mUmEFOFIGIYIZAwDbjcasjGgZKDIEwSlAipRIqUYipKyKZKlJANxE03GE6SOaNCjKMqTJUO2Wq2/n+b0bMlEfm/Q16OHTz31eRyYWdL0Hn8Evf5GejU10YY9MdnoeXsPdb/nVu8/Ra/I+h9Pn2Oyv1+dJreUCsYopqu56ue2cO1OnVlnZrM6I4dOaVAQCYNMA0VQrKkYgc4B0dHGdd04brr0YLTTSnDBgEqYwTAYMSkqTTlTZSGSRbBDAYCUokRpIRlAhCUYhGUUADpDXowJkDJVfopnytsVbmRlIlzVaVuZarKekQxbehn1cqRsjjRJOKs2zLuSsjModsalC4yyq6GlmLeo4z6UdOc+lCMJqpqA2qBygMTJKgIEwSaIxsiQjNEFOMQGhNMAIs14NhZh6fLIASpSREZKdDLp5dYeO9bxfB7/MZ9Wfz+iF+KO+XQlhsTurhRxrr8+q7Wanon155oW22ZrLLlotFL3/TfP8As7no6rH7PLRGUe3IQqEJkTQkxE00AAGERlDCC+jZVVHV59lJJQhghlO2uwlJSG01cozoYxplIkxFtplWnOkQFbegzEgRJJElGAEAIIOCKEq0UXASaESI6Kmd8Qc5lV8rcrK7o87TZe5Ixrz26c9MOkEGwAuzVztnK2U3GFM5WFOTpYdHbG2SqvXSsXOaZI6s+lpc8MsNue1LTIxGyC5auopOObseqhtUMVDBA4SmiM3tMMtIZs+qUc6GugqL5GYsrACBSQhkqUkqSOerNFEvJ7KKMGLwe7pc3l1zUskKfT5NComzbF1XL3c/Wusy3FE6Y0tvPvNtnM1G+uWNro+t8H6TN7Nd1X0PEk10wgNRJiRTEAaIYAAAUNCOysJ1uIxMGmAFSshYSbYmxRydKRYRlvvy5mjSyJKmSvJsy9JWhrLbi2FdXReXMjoq0gpISahRcArlWig4ok0RGgAjv2uOs1yLjJbW9L3VPDRlrz6Tgl1iTVAEAmPXk0Zu6UX57XKqO1+OzPqabcNsa6FEndjmXUMrRKmWVmexFk6ZyzqnSuh1SkXM1496AdAEoAKSYASvVlkmuu0yyO40UZwKZW5xYduOIsIQyUT0rljpzSxuVni9ceXu5ng9eKvbz+fajFZj68nTXDtxtk1cygUWSnU7L7q1NOE4y5dmfaZOlzepVircWydK+u2+P9r245V1Ie3y863bps5J1K7OfDbVZTn6OMqYADEMEMEwQTZEtvMhpurA98jDvr2F1tLJFOmWrPuRz7dUdLmGBNSiNV0LI0a6a5qkug2Y9Ebbs9vMsmumskdUNTLCVYQIircEEAkwSYIYegcDWdKisKZxv3Jqb5XBn2ZfRIqS0SkhJuWEr9OWa9mTcbsqnZUOqdelrccrAcQaKcLIqm2QLSKLHMUb1m5iFPSVwlHWhogAlAAaYMQNXxdbBZQnSaFgkIVVLs5m2qMakoRJSm/PrrLk04+e9eTo1fM9/O5/a5Pn78vPdCax5+lX258qvrLpz5MerBOY+gkwWaXbRDWjNbJSzqrdWXwkU2VwToSwbEv9R5b0SdeOw+l4adE1qY6enXWO6d1ixqlKiSlQwQNBDVA0e/Fuq9xjrJoz3DjKCw1VXCqujFG7LqlVd1RKvTQRnOQi14URkaSIVmSFtPQ5RDRox6pL5xfNUyOpRz+lzqrg4Ci0JhIhoABDD0F2XTcxzbcVLVRpLCmObTVKPaJNaRJOV6ZS5qbYTgLllVbVYOqVNkXmv20wUMXQ884tjCk1LNZV0Y1mmWYl0xy11082KKzijdcWhADE80ABqYRlAd1BHSMGrIddJddj2VjlrRVZTXFePTmAIxfs5vRrFbKnl00c7N5v5P1vax83Rw3vwdGPbFRI74rnKzWa46mYMnarueJd1Lzl2ddWcpdWJxae+l8tR67HHma9+SSjRm0Zmrt8H1cehuxP6Xiuqut3mCjCyxUW1zFbSSQQCYACARgD15J271KzWYWTAKq02yyEaY53bboxyjQ8zXVRGpNV+C9dazywdtF9Kq/KZK5R6ACHOos36eRblrpsVzkz6aDNHTSVgSgCAAACGHQ24re2OjCufGrTm1ZubNbn6yIjoGmK6q/K2ym7lYqwlklGSpSluOUjLFbCW16msWq6uZKLIqtptqGC7J0TiGqNBJBmjGrWiMZwKGnKAQ7qdBbz9uKEMpDUKMkRTQQkipyIUmoUZwguoa6FnXHtT5P0/k/lfXnu5nWnPomnL6uFEJRnSdtM7L50zssEazKdNlSi0MHaiRZGFkDk8T03E5ubMliX+w8h7TM7MKrvp+JSnluajPKzYs6slkcVbVhBNAJgAg0DEqt38y+upKjRc0K2Q5KBKULFc87jRZmsyvzSz267cd0XQIRJTjRztWTasChMiJKJGLgktOKUbsttVzfKnQYqujUmBbsy1JkIYIYb5xO+ZTrC+eYynGJTBDcXUtmK/DQpvlchqjpGYZlkFAvjGoqlXPqtLLOVxztVCMwVQj0AFACgOBqUpbHZLZm1YsMwHQAZo0D05tCX5NdK5DXkgSAiAIBJqEnElFxhxZLEErRDz9/GV6bfmfUXUxbtcejg6HL9HKtxlnrKUZVZOu2yTHrMZJ1IC1yjOwY6VdkDNx+zycOTG+rlL/Z+M9kxYmvoeNIKSDWUgRSJC6WLRZRTKKgMAABogAAosrLNl3PvrXCqRpVW1MkrCi2c82mmyqr76dESjXGNTjZi00bJVyqelm2zK2qlEhBW4ohBup0wua9FNqW0zhUVEjLDfWZBqUAjooPRkAlGgGgYAMkivL8KLrLOdpWmEUzrLCjSqzzsVZqpVdDEKJqBp0JoABico1KV3ylFssplrw247RxVSItQRJLVj0GueZZtnPlHRAREkRBWhSdK05C7dBz311HDr7PKlrUozUVOrh24E93E+Z9K7dRovPbh7vM64wnKL07EuTfc9K3DorY67NyAlU5QuqMnLUSlEK5wWnldbl5nMpvr4yz2njPaa5JOPu8yBaggsAGXry7SevnbrMuDoc9WIGAgANWMqAoAGBSadj6nL1GhwvTRJBFSVLVmtzXOq2CFlUStzXkqbalrzb69Tl16M9Rg4wgUbLsGnWbEXme9zsrjozlqpaRw6ssqGS7013yCcA0rACSmK3RPmLiXFW51LbWhK3MqRZDKiMcnYoC6EBQBAACaACBphfVuluK3zt0oLKXK6nL3axmkRtYjBbsWvMWO2ukwUGoVtmqMkOvnywnSacqnuUrzzrSXhYPU0nBW7Crz683HrVwfVcb5/vq63N6WLZ5q6PSV1a56vLo7dlnC1aMx0tvH6NX57MemvRwaz08/LatTvrDspRnVZXzOpyI5zru4S72/mPYd/Nzq+pn9XHEpRsQFJgj0Z2nTt522zHl6nMABWJoBJbdGTXWJdLIZxxRgDB0NNJ7MM66ap0JGU7pc027Hqolm3xayEq6lGivTTXKww5unjrFGUISkkdtMzXs522wLM9ixOAmNVIlCJBpTO2VJEMTUBj15tmJojKvjbVTNVVarJThblXl2YNqYOPclIIjJBSaxUogACalYAAGjdk14pntswqnpcZeb2ORtBs1YjFQxEMliSSIYA5S6dNOjJ49mck7STPVsy1ZOM1rp11xlx9So5ebdj4+izm9aHk9FXH73Jx05uHoQb5uXum8+f3dGdmC61Sw63L6Mu7NonucOjo82WU8OomunfqYdVVeps4/V5EnO0Q73J1d90/b4a6N8emOa9d1canv84wNgmCOyuwvx6M9gAo00Ygs14ujUq51Lmq11JnclQDhMVEoiScJEp1yqd1MjrSwa4IN1fKt4SrHUI3V1VjszWQiCIGJhE7KCtNMWNNiZITAZpC2rpws5r05twApuLW/bk1cltMp81N8JFkSOTsyZttWKEOxpGjQQSjNJ7aXjVtcr8XLl6VNnOJx6gCAZWjVj2c7dG2HKqdV5XzOnzOkQGqlJLElEEyBSkRv0aMMb3ZpaDVNMi2VRTK0rPT0MYjSVjjrRlq6Hn8d+TZmz/K/R+rjXZ1+Tiuszs8tKWesY2V6iiKyIIN+HdLrnVZ1zXg6mauOdgjhW91mcvhZXyOzwpF73znrZzrnTL2eTRW46lV9N6FFlZyYygrEEnGSOLSiYiadgDJb+furRGqdZ9VlqcSG3GqYQKTIKcQadkmmSnXKtPU4l513h1YTouoIyqs1JZtKjLk6ULOUW1UCcAAwKYMbGElMNFlwgIzy2tOdDYukxgbNolt1ZNuGhxOFiVZ9zfnww2uqS6RoQxNWIiVlV0a7qa+Vunjvq22iWFGPpm7yzpZtMra1J7MV0dOWc8+p02XVzc/QwdQwtSYKMiIkglvxX5aHlli6YVKNLziX105q6Jz5Vtz5s1dh8+RrWWZf53uY8erzGXdh+T+j7nW4XoOny8fD7HCvOALPRxDUSaFGUrF0cnQ1JNPeZRkrIDSynB2SqkrKOD3Odi+h7Pk+1eW+Tfq8qV6ucNppszU9Cg59W+04p1cJRKMlaAAETBBp2y6vK6Fl8LKKL8U00crfgli0iaShiKkDBgg0VOUHVmjIHTu418nUhGRVF1WayiZXz+hSYHOuVikDGOSkgyVKyNhvsV+GQ1C0SRcVSRpiQdgChoFEAAWAIaCABRhAywNco807IacXLOURRszVOym6q7baM2vFZDqcohr38jTi7SVnC4MHS5ndIT1YtEAAAJZ0OXry2WVT5rILPLreSVmjLKi3U8zsuoVC7o1ySmu1VXl3RmvGR9ByPn/bh6PyPsecxcDv8DXCkHjomOoKVNPHW16vQ810tTrS8l1dTtKp6xNwlTBIQcCrTlhnV99PSs6izL1/O3PErm6/mXam6nPGJ34Li7LOsjm346gBKAAAjBj6fM1Vri52WUzZzs19IlIiI2F8NBfOm6yECFZVdQNoJOISuzM61nI22TsVqUR1UClTaV83s80oY5SQxtSHIdhZC033Z7sGBLnr1x1jnwlD0ECGIlAQwBNA0wQ1A0DcWTvoujU61ztd1WqqnZHKyAoc8efd7PPyImQlpIixzqIv6XInnW3A4VIiDIisQAIbUo0befry2Z4V4aZ5g0Z41Vqecsaogb3jVaY42bY54mbznf5Xl93N9h5f1Hl9ebgeh8/rnnUo46MFYQkAp7Kx71dvFE9dWkVZCGhijKFOEopDPvoz0u9Jz9/o8c5Z5dvNojVBk04L61QhUSsx6CdMqyeB5iICtAg0waCe3BvNFldWpsozZBqDJNbYy23OoaK5FtdasvMMy3nasg3CRJIhpAW1M6G7h6NTq1xkyo2TWnn9PCZm3KMYSluMmnTMJXLmrsqtQERTTfh65oiHoAECZKAQAqJwnFt0dHNmp6LXjnSprIShqO2kOjbyjLs04t+LVCdlV3xjEMGjN0DTHKNkWTnCXIaKKbTVgKkEACgAABfLVlZbXLmtzWUF4gjVooqakJRVdRpYOZRZXImIk5+jNrzu6MoNcrgdzieL35wXPoRWddRzxenq4Vup2ruTp3OpXVbrmkGaxgoSiREqucOvZqcYerwSnjt1nUs4k7cczZTVBJacFy6MEueTjFgNKADExiYdDn7E6Mc3OstqiwaCW/BcXTlos57tgaVRZUnK2zBi62WXG92SKxA01QwgAss14g6ujhTs73IqUTakpJTLbpbIwz1BnNzw5tm2aYTeS4s3QxdcYW49zBDByk778OYXUaNoN1mDZhPNdKKdNdpVz9+DQTKQMe7BdHQKZcqpWYaqrF1Npw9VPQzaJ2W5pm1ZcsIPqASgOEMVDQAGq1aOaFkjCMJ5zXLGo3U4lp0Tno2VY69OosEU1mKJ0Z8yst18DXNdZc+BRxexxfF764N8u0FNLWpq2oc70J36Ledb0LLjka9OWctrolZOKVzp09OXfy4tlS6c7wlrGeUZWXpMzX0W1ZCUYya8usjVdA5NdtQAKASgAwEAVCYEjYmM3YLJSgy63NI6F+DVWiqFaW06J2c6TrW+q22OUrqQAG4g3FjE7CSZKUZjYxyHbr383pYRhOFmka5q7ap1MDLPllT2xPHtxdQBRKOiWy6RyVYOtnrnsWzsrDpW4dvNTfVfFXL6XO2QykAEZIU4EuqmAAFNz1xTqsni5ZFqjnPDkw6eDorAtTTBCViBiIv6HJ0R0Z0z5pU2UVeoyQg6K0FEwrjGtCgiZQi+MYxh159BpMuBrTx7NXl9fmXqx+f02RYsYWsz2XWXVd07NSM3LWIVWwkQ4yO+jo6xup6B6/Hy7d87MM9jueY73LCdkbKL8li6FSkNHNtNiyRNNNcDKAoBKAAAgADUrNN91Nj5vRoM0hqMZft53UsyPakyy0VDpz010c2WENIGSuM723HNOrkMkh2DGOcZjlGVNjlnuwbS00LnK3dPLGaiqTUZYqL83fFnN6HP6ADVlpzbcJl0+dzV7qE5kLqepuMg2Y7sttM8ORGMti2rRFdGqZiOhiitwdsmmF1Og334Jc7ueJ5aHhlbueGUbKqK6yiOlaFK0AAgEEnBxdp56OquTrjoEZ5ViEmRRBUlaY0lSeaRrro5ct1USWCklao5Xk9vd4b2ceuCSgtkqWuzRh06moJaii67l1lckoxkS7PH7fTnpKp+jyuI0lNOygsFsY7M1tFpYiKVX5dCziqhU0UCAACUAAAAEbt22RsRZK2uRzoa8ypgGrNM3yshZdnrzRXXJVGM1JAdtabrUlBZdWGPYwnPiwJElbGjlGStpjsrZ1J455bLMtuJOuUS4ZlixV1+vFlYUxNXqy6Mtzps5WVUq6w1X09YmAAQJqGBVmvLsiMdOfNuz23HFOtjrK5Rp6M2g335dPOylVLKEQq5TM2GTdjrBJHWkZRlAATCdW+qXI0IAoWzHrrdKMsyuIi4iFCsjU0ghRPlylU1KAEU0ubl9TmeL31Kb59ZQqpktVKNd/NmvVu5N2p0IZJ3N5Vdorh2HV5ezpynpyT7ebUlelZplWJbIWULeVzLb3JQ7EZlDMa6KxRNAAAAAKAIThabNEbbmFWp2Y9JaU87sJeLLo4BSiyyAhKQkVJCjOJC2t2b42TsrlDSZcV2YlKMx3y3Lnz9jImKSajCnOO2NRKOCsjdmVU66BGgk88g9cGnA5aCvarudrhfCQtRkufto2wrYtsY4jQokiRZpNUUV7M8TnXdKiNaHN34NI30W3W7Tguw0SySyuKkaipy2ZL8VUuJ0rQSgAAy2Vt8vHevIIZCsrcm63maycr74xLdE5sdqsojp5q5axyxYAhEZqU1j5fW5Hi+imjGnXNGWrfZHKn1JHLv6NlY9F73ISZqJjqKt1a413eC9n0469uC256Di9ZIydlgpWZrIOpxEYsl1MAECZSlZeuEBAGqGIrK5muc7bnOa5GKW2ZilrZkx9rnriaYKSAeuzGdnEYo31pSOJt3cS6zqw5+eyURkrIXmy6SWdEr45hbXSbKe7DpjoQqhzap4rZNFMYG4zmXDafrwSTl124yNejlxjpS5Ok3KFmVdVsNHZOWXNy9LnbIIrPRmuNmnLdlbVU4BWorU4MO/FXPknvWvbg2ZWyqeE4FVayJmvn7+dVBF7oCVtENpnRspnLbi0VJzjfz1EKBEQvzxjq3cRHfXAts7XDllWZGUAiGmKlZn4+qXD7vD8vqipRACjRmvNM63pYQdOUJWNqaxjOFnQz9Pzvo8fkJVxxPadT516fD02zFq1mJqOmc62OznvXktVMc9jQoYmOb1EE85SxiGCAolGSb7q7kU0ELIXWVzc0WLoc23PONkqns1WYzbJM+bRWuN6YpzITiK2pRtyIsk4y1JX57zq2VWyytpujJi3YbQFU789h1iqfOO3HfFtUqktKQ4qlD0ZbiDERIiiTgGi/Co6BgRvpzFtkYuwiyG4tdV+XoyRsbxYJwsvKoRflrnbzVZXts3czVLrdDwuqVZtM0Y186/n6o4u1oJRpJOUXLuthOWOYxF9CQCQ0krRCBCRKVYCByhYQl1M0ue67NjpDmXcXx/R9Hwu3xs2tNagnFC6mdayuazcZWylGdgLnrf6HPr9HjPEe4+a745qraclKK5u76z5rpxv6c/E72vSR5erUsLXvOYsjvEGxHbHXY5pCz3UFCkqAAEqk4tNwa7M5qaZLZX1nnoIy4OjzaL6dUuu/NKy+VNiZK9AYy2048bahIAakhKOqq9l99lL3GWG7S5eVVtybRBKTrDdq5Dk693E0SdWvEstpiI58ZLvlKUQBDEwEKyIMEMQMQNAMiFm7n3R1SiGV1BfpVdXpiBOMc3JryaaNmHWbAWbLPozGmUJQ+R1+TbWItkRJZESSU62dPlyqUAUESgEJWyM8NdK1K+lIwiAStmqtVcee71m6fPdnNtq05nD7PD8vt6z5XUzqmNle8pMRThZbbZCRNwlUyjFLPtVdft5nJL1eSr5n9D+eYRrlDNISjmKEo5dDr+Y28+vdq51eOnZ6Xmb9PYavH6NT1a81dvPfnxdWs9KeW/UnTdC5xqS1lAAgoBJt1ZNiRJzqi9TSFiCjDozVPbi2mydUhVacyO+iBDTi1VXye5yDOSUE43F2h2azfbiti0hYR0VTllh3UHPjry2
